// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4796ad94-0eca-4f30-b205-d7a8844fa89a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FXs9pyo8C",
    "aws_user_pools_web_client_id": "70bldclep1vi1gp38q0vle4igr"
};


export default awsmobile;
