// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7bf381f9-0d68-401f-81b0-ee4a0641fcda",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YrRAO2YZe",
    "aws_user_pools_web_client_id": "4lo3r580pbc0lulfikditchof8",
    "aws_appsync_graphqlEndpoint": "https://56gph6deorcchdqysfmwfqvldq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "photoalbums71cecdc2603a42998e406bac6622dda7",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
